### ISSUE TITLE
5.0.3 version does not can't scan BLE Beacons devices on Android 12+

### ISSUE THREAD

**Issue by fufylev** [PhilipsHue/flutter_reactive_ble#664]
**When use a [flutter_reactive_ble](https://github.com/PhilipsHue/flutter_reactive_ble) scanner does not see any Beacon devices on Android 12+**
I tried to scan for devices - scanner does not detect any BLE Beacons devices on Android 12+, while it perfectly detects all of BLE Beacon devices on Android 11 and lower.

**To Reproduce**
1. Clone repo
2. Run `flutter pub get` and `flutter packages pub run build_runner build --delete-conflicting-outputs` in folders: `example`, `packages/flutter_reactive_ble`, `packages/reactive_ble_mobile`, `packages/reactive_ble_platform_interface`.
3. Run an app on Android 12+
4. Scan for devices near the Beacon sensors.

**Expected behavior**
While scanning all BLE Beacons devices must be detected

**Smartphone**
 - Device: [SM M127F - Samsung Galaxy M12 32GB]
 - OS: [Android 12]

**Peripheral device**
- Vendor, model: [AprilBrother, model number 2.0.4]
- Does it run a custom firmware / software: no, firm revision 4.0.8

**Additional context**
To start an app from example I had to fix some bugs
1. Added an import
`import 'dart:typed_data';`
to files:
```
packages/reactive_ble_mobile/lib/src/converter/protobuf_converter.dart
packages/reactive_ble_mobile/test/reactive_ble_platform_test.dart
```
2. Modify an AndroidManifest file like this, otherwise an app doesn't even start
<img width="545" alt="Screenshot 2022-12-25 at 13 20 29" src="https://user-images.githubusercontent.com/35691656/209461426-fa4c605a-be5c-422b-be62-130567ead52f.png">

**Comment by watsmyname** [comment]
It works in my Android 12, not using code from example folder though.

**Comment by PlayCulture** [comment]
I have an Android 11 phone here that can scan for iBeacons and an Android 13 phone that cannot.

**Comment by PlayCulture** [comment]
I have observed the following, running identical code:
- Android 11 phone can detect AltBeacons and iBeacons
- Android 13 phone cannot

I've also seen the same behaviour with other beacon-sensing packages for flutter. Is there a possibility this is a permission-realted issue?

**Comment by PlayCulture** [comment]
Update:
- Android 13 phone can detect AltBeacons, but **not iBeacons**

**Comment by JulianAtTroido** [comment]
Based on this [Stackoverflow](https://stackoverflow.com/a/62473780) it seems that the underlaying Android library [RxAndroidBle](https://github.com/dariuszseweryn/RxAndroidBle) which flutter_reactive_ble uses defines the scanForDevices without on empty ScanFilter: see [here](https://github.com/PhilipsHue/flutter_reactive_ble/blob/4b5ed35fef136569c1efa56aa096919c839b9101/packages/reactive_ble_mobile/android/src/main/kotlin/com/signify/hue/flutterreactiveble/ble/ReactiveBleClient.kt) line 70.

**Comment by PlayCulture** [comment]
Thanks again Julian - I'm looking forward to testing. It sounds like "flutter_reactive_ble breaking iBeacons for everything" might deserve its own issue thread? I'm curious what could have changed from Android 11 to cause an issue like this.

**Comment by JulianAtTroido** [comment]
We just fixed our "problem" by using the solution from this  https://github.com/PhilipsHue/flutter_reactive_ble/issues/566#issuecomment-1181665284. 🎉
It is also outlined in the readme of this library.
Keep in mind, that you might need to remove `tools:targetApi="s"` as compared to the readme example.

Please tell me if that also resolved your problem.

**Comment by PlayCulture** [comment]
Thanks again for the advice, much appreciated. Unfortunately the only thing that has worked for me is to completely remove reactive_ble. Now other ble packages can sense iBeacons again, so i'm up and running. Damn!

**Comment by fufylev** [comment]
> We just fixed our "problem" by using the solution from this [#566 (comment)](https://github.com/PhilipsHue/flutter_reactive_ble/issues/566#issuecomment-1181665284). 🎉 It is also outlined in the readme of this library. Keep in mind, that you might need to remove `tools:targetApi="s"` as compared to the readme example.
> 
> Please tell me if that also resolved your problem.

It did not help me. I still can't detect iBeacons on Android 12

**Comment by fufylev** [comment]
> Thanks again for the advice, much appreciated. Unfortunately the only thing that has worked for me is to completely remove reactive_ble. Now other ble packages can sense iBeacons again, so i'm up and running. Damn!

Which package you've chosen?

**Comment by PlayCulture** [comment]
I'm using flutter_beacon - As of today we have broadcasting and sensing working on Android 11 and 13, as well as iOS. Hope that helps!

**Comment by fufylev** [comment]
> I'm using flutter_beacon - As of today we have broadcasting and sensing working on Android 11 and 13, as well as iOS. Hope that helps!
> 
> Top tip that might help you: iOS handles bluetooth permission weirdly, so you don't want to explicitly request it, just go ahead and try to use bluetooth and it will automatically request permission. For Android you should request first, then use

Thanks for reply.
I've spent several hours on this flutter_beacon but still not able to scan any devices. App crashes in 2 seconds.
Which region do you apply. Would be very appreciated if you provide a simple code example that works (fufylev@gmail.com)

**Comment by PlayCulture** [comment]
So with iBeacons you have to know the UUID you are looking for before you scan, you can't just scan for anything that's around. Here's a snipet from our project:

```
String Uuid = "00000000-0000-0000-0000-000000000000"; // Put your known UUID here
String Identifier = "com.playculture"; // Replace with your project ID
String Layout = "m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"; // iBeacon, must be this value
int ManufacturerId = 0x004c; // Reserved when using iBeacon, must be this value
```

For AltBeacon you can do all sorts of things, but iOS won't be able to transmit anything other than iBeacon.

Hope that helps!

**Comment by dkozenkov** [comment]
> We just fixed our "problem" by using the solution from this [#566 (comment)](https://github.com/PhilipsHue/flutter_reactive_ble/issues/566#issuecomment-1181665284). 🎉 It is also outlined in the readme of this library. Keep in mind, that you might need to remove `tools:targetApi="s"` as compared to the readme example.
> 
> Please tell me if that also resolved your problem.

Thank you for your link. The problem is actually solved by making the specified changes to the file AndroidManifest.xml, and I used the string 'tools:targetApi="s"'. It is important to note that to start scanning, you need to request the necessary permissions directly in the application. In my case, I requested the following permissions: locationWhenInUse, bluetoothScan, bluetoothConnect. For this, I used the 'permission_handler' package from pub.dev.
